// Registration Form Actions
export const UPDATE_REGISTRATION_FORM = 'UPDATE_REGISTRATION_FORM';
export const RESET_REGISTRATION_FORM = 'RESET_REGISTRATION_FORM';
export const SET_FORM_FIELD = 'SET_FORM_FIELD';

// Registration Submission
export const SUBMIT_REGISTRATION_REQUEST = 'SUBMIT_REGISTRATION_REQUEST';
export const SUBMIT_REGISTRATION_SUCCESS = 'SUBMIT_REGISTRATION_SUCCESS';
export const SUBMIT_REGISTRATION_FAILURE = 'SUBMIT_REGISTRATION_FAILURE';

// Form Validation
export const SET_FORM_ERRORS = 'SET_FORM_ERRORS';
export const CLEAR_FORM_ERRORS = 'CLEAR_FORM_ERRORS';
export const SET_FIELD_ERROR = 'SET_FIELD_ERROR';
export const CLEAR_FIELD_ERROR = 'CLEAR_FIELD_ERROR';

// Location Data
export const SET_PROVINCES = 'SET_PROVINCES';
export const SET_DISTRICTS = 'SET_DISTRICTS';
export const SET_SECTORS = 'SET_SECTORS';
export const SET_CELLS = 'SET_CELLS';
export const SET_VILLAGES = 'SET_VILLAGES';

// Skills and Professions
export const SET_AVAILABLE_SKILLS = 'SET_AVAILABLE_SKILLS';
export const SET_SELECTED_SKILLS = 'SET_SELECTED_SKILLS';

// NID verification action types
export const VERIFY_NID_REQUEST = 'VERIFY_NID_REQUEST';
export const VERIFY_NID_SUCCESS = 'VERIFY_NID_SUCCESS';
export const VERIFY_NID_FAILURE = 'VERIFY_NID_FAILURE';
export const CLEAR_NID_DATA = 'CLEAR_NID_DATA';
export const SET_NID_VERIFIED = 'SET_NID_VERIFIED';
